#!/bin/bash
mongoexport --db sos agents > backups/agents-*date.json
mongoexport --db sos cargo_categories > backups/cargo_categories-*date.json
mongoexport --db sos clients > backups/clients-*date.json
mongoexport --db sos container_type > backups/container_type-*date.json
mongoexport --db sos costs > backups/costs-*date.json
mongoexport --db sos financials > backups/financials-*date.json
mongoexport --db sos hcodes > backups/hcodes-*date.json
mongoexport --db sos insurance_types > backups/insurance_types-*date.json
mongoexport --db sos mongoose-auto-increments > backups/mongoose-auto-increments-*date.json
mongoexport --db sos notes > backups/notes-*date.json
mongoexport --db sos payments > backups/payments-*date.json
mongoexport --db sos photos > backups/photos-*date.json
mongoexport --db sos ports > backups/ports-*date.json
mongoexport --db sos quotedetails > backups/quotedetails-*date.json
mongoexport --db sos quotes > backups/quotes-*date.json
mongoexport --db sos sessions > backups/sessions-*date.json
mongoexport --db sos shippers > backups/shippers-*date.json
mongoexport --db sos shippingprices > backups/shippingprices-*date.json
mongoexport --db sos states > backups/states-*date.json
mongoexport --db sos system.indexes > backups/system.indexes-*date.json
mongoexport --db sos task_types > backups/task_types-*date.json
mongoexport --db sos terminal_insts > backups/terminal_insts-*date.json
mongoexport --db sos terminals > backups/terminals-*date.json
mongoexport --db sos truckers > backups/truckers-*date.json
mongoexport --db sos truckingprices > backups/truckingprices-*date.json
mongoexport --db sos user_categories > backups/user_categories-*date.json
mongoexport --db sos users > backups/users-*date.json
mongoexport --db sos vehicles > backups/vehicles-*date.json
mongoexport --db sos videos > backups/videos-*date.json
